const types = {
  //RESTAURANT ACTIONS
  FETCH_RESTAURANTS_SUCCESS: "FETCH_RESTAURANTS_SUCCESS",
  FETCH_RESTAURANTS_ERROR: "FETCH_RESTAURANTS_ERROR",
  //UI ACTIONS
  UPDATE_CITY: "UPDATE_CITY",
  UPDATE_PRICE: "UPDATE_PRICE",
  UPDATE_RESTAURANT_NAME: "UPDATE_RESTAURANT_NAME",
  UPDATE_ADDRESS: "UPDATE_ADDRESS",
  UPDATE_STATE: "UPDATE_STATE",
  UPDATE_ZIPCODE: "UPDATE_ZIPCODE",
  UPDATE_COUNTRY: "UPDATE_COUNTRY",
  UPDATE_PAGE: "UPDATE_PAGE",
  UPDATE_PER_PAGE: "UPDATE_PER_PAGE",
  DISPLAY_REFINE_SEARCH: "DISPLAY_REFINE_SEARCH",
};

export default types;
